version: '3.8'
services:
  proxy:
    image: nginx:latest
    volumes:
    - ./services/proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
    networks:
      - localhost
  frontend:
    # volumes:
    #   - ./services/frontend:/app
    environment:
      NODE_ENV: development
    build: ./services/frontend
    # command: node .output/server/index.mjs
    expose:
      - 3000
    networks:
      - localhost
  backend:
    # volumes:
    #   - ./services/backend:/app
    build: ./services/backend
    # command: uvicorn main:app --proxy-headers --reload --host 0.0.0.0 --port 5000
    expose:
      - 5000
    networks:
      - localhost
networks:
  localhost:
    driver: bridge